# Generated by Django 5.1.2 on 2024-11-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_boletin_archivo_pdf_boletin_imagen_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='tag',
            field=models.ManyToManyField(related_name='boletines', to='api.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TagBoletin',
        ),
    ]
