# Generated by Django 5.1.2 on 2024-11-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_boletin_tag_tag_tipo_delete_tagboletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='comentarioboletin',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='comentarioboletin',
            name='Boletin',
        ),
        migrations.RemoveField(
            model_name='boletin',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='boletin',
            name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='boletin',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boletin',
            name='categorias',
            field=models.ManyToManyField(to='api.categoria'),
        ),
        migrations.AddField(
            model_name='boletin',
            name='regiones',
            field=models.ManyToManyField(to='api.region'),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='ComentarioBoletin',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
