# Generated by Django 5.1.3 on 2024-11-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_poblar_regiones'),
    ]

    operations = [
    ]
