# Generated by Django 5.1.2 on 2024-11-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('archivo_pdf', models.FileField(upload_to='boletines/')),
                ('imagen', models.ImageField(upload_to='imagenes_boletines/')),
                ('categorias', models.ManyToManyField(to='core.categoria')),
                ('regiones', models.ManyToManyField(to='core.region')),
            ],
        ),
    ]
