# Generated by Django 5.1.2 on 2024-11-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_boletin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletin',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='boletin',
            name='regiones',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Boletin',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
