services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    working_dir: /frontend
    command: npm run dev
    
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
