# Usa una imagen base de Node.js estable
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /frontend

# Copia solo los archivos necesarios para instalar dependencias
COPY ./frontend/package*.json ./

# Instala las dependencias usando npm ci para entornos de producción
RUN npm ci

# Copia el resto del código fuente
COPY ./frontend .

# Expone el puerto que usa Vite
EXPOSE 5173

# Comando para iniciar la aplicación
CMD ["npm", "run", "dev"]