# Generated by Django 5.2 on 2025-04-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='rol',
        ),
    ]
