# Generated by Django 5.2 on 2025-04-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_role_customuser_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='rol',
            new_name='role',
        ),
    ]
